WITH V_T AS (
    SELECT 
        MAIN.CAR_ID    
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY MAIN
    GROUP BY MAIN.CAR_ID
)

SELECT 
    V_T.CAR_ID,
    CASE 
        WHEN A.AVAILABILITY ='대여중' THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM V_T
LEFT JOIN (
    SELECT 
        DISTINCT HISTORY.CAR_ID,
        '대여중' AS AVAILABILITY,
        HISTORY.START_DATE,
        HISTORY.END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
    WHERE 1 = 1
    AND (TO_CHAR(HISTORY.START_DATE, 'YYYY-MM-DD') < '2022-10-16' 
        AND TO_CHAR(HISTORY.END_DATE, 'YYYY-MM-DD') >= '2022-10-16' 
    )
    AND (TO_CHAR(HISTORY.START_DATE, 'YYYY-MM-DD') <= '2022-10-16'
        AND TO_CHAR(HISTORY.END_DATE, 'YYYY-MM-DD') > '2022-10-16'
    )
) A ON A.CAR_ID = V_T.CAR_ID
ORDER BY V_T.CAR_ID DESC
