-- 코드를 입력하세요
WITH MAIN_T AS (
    SELECT *
    FROM USED_GOODS_BOARD BOARD
    WHERE BOARD.STATUS = 'DONE'
    AND BOARD.PRICE >= 700000
)

select
    MAIN_T.WRITER_ID AS USER_ID
    , USR.NICKNAME
    , MAIN_T.PRICE AS TOTAL_SALES
from MAIN_T
LEFT JOIN USED_GOODS_USER USR
ON MAIN_T.WRITER_ID = USR.USER_ID
ORDER BY MAIN_T.PRICE