WITH V_T AS (
    SELECT 
        MAIN.CAR_ID    
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY MAIN
    GROUP BY MAIN.CAR_ID
)

SELECT 
    V_T.CAR_ID,
    CASE 
        WHEN A.AVAILABILITY ='대여중' THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM V_T
LEFT JOIN (
    SELECT 
        DISTINCT CAR_ID,
     '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
    -- WHERE 1=1 
    --     AND TO_DATE('2022-10-16','YYYY-MM-DD') >= START_DATE 
    --     AND TO_DATE('2022-10-16','YYYY-MM-DD') <= END_DATE 
    WHERE 1 = 1
    AND (HISTORY.START_DATE <= TO_DATE('2022-10-16', 'YYYY-MM-DD')
        AND HISTORY.END_DATE >= TO_DATE('2022-10-16', 'YYYY-MM-DD')
    )    
) A ON A.CAR_ID = V_T.CAR_ID
ORDER BY V_T.CAR_ID DESC
