WITH TB AS (
    SELECT WRITER_ID, COUNT(*) CNT
    FROM USED_GOODS_BOARD BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
)

SELECT
    T.WRITER_ID AS USER_ID
     , UGU.NICKNAME
     , UGU.CITY || ' ' || UGU.STREET_ADDRESS1 || ' ' || UGU.STREET_ADDRESS2 AS 전체주소
     , SUBSTR(UGU.TLNO, 1,3) || '-' || SUBSTR(UGU.TLNO, 4, 4) || '-' || SUBSTR(UGU.TLNO, 8, 4) AS 전화번호
FROM TB T
         LEFT JOIN USED_GOODS_USER UGU
                   ON T.WRITER_ID = UGU.USER_ID
ORDER BY T.WRITER_ID DESC