-- 대여 기록이 존재하는 자동차 리스트 구하기
SELECT 
    DISTINCT CAR.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR CAR
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY ON 1=1
AND CAR.CAR_ID = HISTORY.CAR_ID
WHERE 1=1 
AND CAR.CAR_TYPE = '세단'
AND TO_CHAR(HISTORY.START_DATE, 'MM') = '10'
ORDER BY CAR_ID DESC
