WITH MAIN_T AS (
    SELECT 
        HISTORY.CAR_ID, 
        (HISTORY.END_DATE - HISTORY.START_DATE)+1 AS DAYS, 
        CAR.DAILY_FEE, 
        CASE WHEN (HISTORY.END_DATE - HISTORY.START_DATE)+1 >= 90 THEN 90 
             WHEN (HISTORY.END_DATE - HISTORY.START_DATE)+1 >= 30 THEN 30 
             WHEN (HISTORY.END_DATE - HISTORY.START_DATE)+1 >= 7  THEN 7 
             ELSE 100 
        END AS DR, 
        HISTORY.HISTORY_ID AS HISTORY_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY 
    LEFT JOIN CAR_RENTAL_COMPANY_CAR CAR ON CAR.CAR_ID = HISTORY.CAR_ID      
    WHERE CAR_TYPE = '트럭' 
), BASE_T AS (
    SELECT 
        MAIN_T.CAR_ID, 
        MAIN_T.HISTORY_ID,
        CASE WHEN PL.DISCOUNT_RATE IS NULL 
                THEN (MAIN_T.DAILY_FEE * (100) * 0.01) * (MAIN_T.DAYS)
             ELSE 
                (MAIN_T.DAILY_FEE * (100 - PL.DISCOUNT_RATE) * 0.01) * (MAIN_T.DAYS)
        END AS FEE
    FROM MAIN_T 
    LEFT JOIN ( SELECT  CAR_TYPE, 
                        REGEXP_REPLACE(DURATION_TYPE, '[^0-9]') AS DURATION_TYPE,
                        TO_NUMBER(REGEXP_REPLACE(DISCOUNT_RATE, '[^0-9]')) AS DISCOUNT_RATE
                FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE CAR_TYPE = '트럭') PL ON PL.DURATION_TYPE = MAIN_T.DR
)

SELECT 
    BASE_T.HISTORY_ID, 
    BASE_T.FEE
FROM BASE_T
ORDER BY BASE_T.FEE DESC, BASE_T.HISTORY_ID DESC



