SELECT
    BOARD.TITLE
    , BOARD.BOARD_ID
    , REPLY.REPLY_ID
    , REPLY.WRITER_ID
    , REPLY.CONTENTS
    , DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS  CREATE_DATE
FROM USED_GOODS_REPLY AS REPLY

LEFT JOIN USED_GOODS_BOARD AS BOARD
ON BOARD.BOARD_ID = REPLY.BOARD_ID

WHERE BOARD.CREATED_DATE >= '2022-10-01'
AND BOARD.CREATED_DATE < '2022-11-01'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE