-- 대여 가능한 자동차 목록
SELECT
    CAR.CAR_ID
    , CAR.CAR_TYPE
    , ROUND(CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) / 100, 0) FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON PLAN.CAR_TYPE = CAR.CAR_TYPE
AND PLAN.DURATION_TYPE = '30일 이상'

WHERE 1=1
AND (CAR.CAR_TYPE = '세단' OR CAR.CAR_TYPE = 'SUV')
AND CAR.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
    WHERE 1=1
    AND TO_CHAR(HISTORY.START_DATE, 'yyyy-MM-dd') >= '2022-11-01'
    AND TO_CHAR(HISTORY.END_DATE, 'yyyy-MM-dd') <= '2022-11-30'
    GROUP BY CAR_ID
)
AND ROUND(CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) / 100, 0) >= 500000
AND ROUND(CAR.DAILY_FEE * 30 * (100 - PLAN.DISCOUNT_RATE) / 100, 0) < 2000000

ORDER BY
    FEE DESC,
    CAR.CAR_TYPE ASC,
    CAR.CAR_ID DESC